
server:
  port: 8000
 
spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 1000MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/videos?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp 
mybatis:
  mapper-locations: classpath:com/app/mapper/*.xml
  type-aliases-package: com.app.entity
 
#showSql
logging:
  level:
    com:
      example:
        mapper : debug